name: first workflow
on: push
jobs:
  echoing:
    runs-on: ubuntu-latest
    steps:
      - name: "23f2000573@ds.study.iitm.ac.in"
        run: echo "This is my first actions workflow. This is done for TDS week-2 question 7"